function/email.txt
layouts/_default/baseof.html
src/scss/_header.scss

Changed assets load order

---

content/events/bucuresti/index.en.md
content/events/bucuresti/index.ro.md

Update Bucharest location

---

layouts/events/single.ics

Add location timezone support

---

content/events/cluj/index.en.md
content/events/cluj/index.ro.md

Update Cluj location

---

i18n/en.yaml
i18n/ro.yaml

Modify string content of email updates placeholder.

Modify email updates string

---

data/events.json

Update date and number of edition for next hackday.

Update HD18 date

---

content/hackday/index.en.md
content/hackday/index.ro.md

Add Jurnal Medical back to projects.

Add Covid-19 ecosystem project

---

data/events.json
function/email.txt

Bump HackDay edition

---

content/hackday/index.en.md
content/hackday/index.ro.md

Update HD projects

---

content/hackday/index.en.md
content/hackday/index.ro.md

Add VotONG tech

---

config.yml

fix governmental typo

---

data/events.json

Bump HackDay date

---

content/hackday/index.en.md
content/hackday/index.ro.md
data/events.json

Update info for HD24

---

data/events.json

Fix HD24 date

---

i18n/en.yaml
i18n/ro.yaml

Update 20% URL

---

content/hackday/index.en.md
content/hackday/index.ro.md
data/events.json

Update HD 25

---

data/local_sponsors.json

Remove Cegeka from sponsors

---

data/local_sponsors.json

Update local sponsors list

---

content/hackday/index.en.md
content/hackday/index.ro.md
data/events.json

Add HD27 details

---

content/events/bucuresti/index.en.md
content/events/bucuresti/index.ro.md
content/events/cluj/index.en.md
content/events/cluj/index.ro.md
content/events/iasi/index.en.md
content/events/iasi/index.ro.md
content/events/online/index.en.md
content/events/online/index.ro.md
content/events/sibiu/index.en.md
content/events/sibiu/index.ro.md
content/events/timisoara/index.en.md
content/events/timisoara/index.ro.md
layouts/events/card.html
layouts/page/hackday.html

Add date per event

---

content/events/bucuresti/index.en.md
content/events/bucuresti/index.ro.md
content/events/cluj/index.en.md
content/events/cluj/index.ro.md
content/events/iasi/index.en.md
content/events/iasi/index.ro.md
content/events/online/index.en.md
content/events/online/index.ro.md
content/events/sibiu/index.en.md
content/events/sibiu/index.ro.md
content/events/timisoara/index.en.md
content/events/timisoara/index.ro.md
data/events.json
function/form.json
layouts/events/card.html
layouts/events/single.ics
layouts/index.html
layouts/page/hackday.html

Change date mechanism

---

content/events/bucuresti/index.en.md
content/events/bucuresti/index.ro.md
content/events/iasi/index.en.md
content/events/iasi/index.ro.md
content/events/sibiu/index.en.md
content/events/sibiu/index.ro.md

off locations
